### ISSUE TITLE
Libhoudini fails to start apps

### ISSUE THREAD

**Issue by CCF100** [casualsnek/waydroid_script#17] opened 2021-11-28 22:34 UTC
Whenever I try to start a non-native architechure app, the app crashes almost immediately, with the following printed in logcat:
```
11-28 22:31:34.051  5154  5154 E linker  : library "/system/lib64/arm64/nb/libtcb.so" ("/system/lib64/arm64/nb/libtcb.so") needed or dlopened by "/system/lib64/libhoudini.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64:/system/product/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/product/lib64:/system/framework:/system/app:/system/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework:/system/vendor/app:/system/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand:/apex/com.android.runtime/lib64/bionic:/system/lib64/bootstrap"]

```

**Comment by casualsnek** [comment] 2021-11-29 01:09
What android version images are you using, 10 or 11 ?

**Comment by hcsubser** [comment] 2021-11-30 19:44
does not work for me either, using the latest lineageos 17.1 image from waydorid sourceforge

**Comment by casualsnek** [comment] 2021-12-01 05:28
> does not work for me either, using the latest lineageos 17.1 image from waydorid sourceforge

looks like you are using Android 10 Images ! Houdini wont work on Android 10 images use libndk instead !

**Comment by casualsnek** [comment] 2021-12-01 05:29
> does not work for me either, using the latest lineageos 17.1 image from waydorid sourceforge

looks like you are using Android 10 Images ! Houdini wont work on Android 10 images use libndk instead !

**Comment by hcsubser** [comment] 2021-12-01 11:42
aaa, that explains it, thanks!
Do you happen to know where I can find Android 11 images for Waydroid?

**Comment by casualsnek** [comment] 2021-12-02 05:06
> aaa, that explains it, thanks! Do you happen to know where I can find Android 11 images for Waydroid?

https://mega.nz/folder/N10jGA4a#j8tF2-6LY6Qq5Da2zV0Z7g

This is the link to a11 images, more changes in configuration files are needed to boot it, instructions can be found on waydroid matrix group :)

you can close this issue if you do not encounter any other issues with libhoudini installation !

**Comment by CCF100** [comment] 2021-12-11 18:24
> What android version images are you using, 10 or 11 ?

I'm using Android 10

**Comment by casualsnek** [comment] 2021-12-18 12:41
> > What android version images are you using, 10 or 11 ?
> 
> I'm using Android 10

libndk does not have good compatiblity with the apps, maybe this is causing your issue ? by the way which app were you trying to run ?

**Comment by casualsnek** [comment] 2022-01-04 11:41
> Whenever I try to start a non-native architechure app, the app crashes almost immediately, with the following printed in logcat:
> 
> ```
> 11-28 22:31:34.051  5154  5154 E linker  : library "/system/lib64/arm64/nb/libtcb.so" ("/system/lib64/arm64/nb/libtcb.so") needed or dlopened by "/system/lib64/libhoudini.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib64:/system/product/lib64", permitted_paths="/system/lib64/drm:/system/lib64/extractors:/system/lib64/hw:/system/product/lib64:/system/framework:/system/app:/system/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/system/vendor/framework:/system/vendor/app:/system/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand:/apex/com.android.runtime/lib64/bionic:/system/lib64/bootstrap"]
> ```

since you mentioned you were using a10 and libhoudini which is not supported, i recommend using libndk for a10

I will be closing this issue, as libhoudini does not work with Android 10 by design.

Feel free to create another issue if you have further issues !

**Closed by casualsnek** 2022-01-04 11:41 UTC
Labels: bug, question
